### PR TITLE
Blog App: validations and model specs

### PR DESCRIPTION
**Pull request by felixodette**
- Add the following validations:
-- For the User model:
-- Name must not be blank.
-- PostsCounter must be an integer greater than or equal to zero.
- For the Post model:
-- Title must not be blank.
-- Title must not exceed 250 characters.
-- CommentsCounter must be an integer greater than or equal to zero.
-- LikesCounter must be an integer greater than or equal to zero.
-- Add unit specs for all of your models' methods and validations.

### CODE REVIEW

**Comment by ahmetbozaci** [comment]
# ❌ ❌ ❌ STATUS: INVALID  ❌ ❌ ❌ 


### Hello @felixodette ✋🏼 
#### You have submitted a project, that is not working.
You duplicated migrate files, that's why ı cant migrate them, and ı can checks the tests. Kindly fix it.
image
image


#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


### Cheers and Happy coding! 💻 👏
coding

___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

_Invalid Code Review Request **does not count** into the code reviews limit._

___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by felixodette** [comment]
Hey @ahmetbozaci ! I'll need help with clearing this issue. Any chance you have a minute? Reach me on slack?

**Review by FrederickMih — APPROVED** [review]
Hi @felixodette , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- GitHub workflow has been followed :heavy_check_mark: 
- PR has a title and summary :heavy_check_mark: 
- No Linter issue detected :heavy_check_mark: 
- Add unit tests for User, Post, Comment and Like model :heavy_check_mark: 

## Optional suggestions

-  Let's set the default route of our app to avoid the Rails default welcome page.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by felixodette** [comment]
@FrederickMih Thanks for the quick review. I'll definitely do the suggested routing. Have a great weekend!!!

**Pull request merged**
